/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prontuario.view;

import br.com.ifba.anamnese.entity.Anamnese;
import br.com.ifba.paciente.entity.Paciente;
import br.com.ifba.prontuario.controller.ProntuarioIController;
import br.com.ifba.prontuario.entity.Prontuario;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Glauber
 */
@Component
public class TelaCriarProntuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCriarProntuario
     */
    @Autowired
    private ProntuarioIController prontuarioController;
    
    
    public TelaCriarProntuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        lblPaciente = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        txtQueixas = new javax.swing.JTextField();
        txtSintomas = new javax.swing.JTextField();
        txtCondicoes = new javax.swing.JTextField();
        lblQueixas = new javax.swing.JLabel();
        lblSintomas = new javax.swing.JLabel();
        lblCondicoes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalvar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 90, 40));

        lblPaciente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPaciente.setText("ID Paciente");
        getContentPane().add(lblPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        getContentPane().add(txtPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, -1));

        txtQueixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQueixasActionPerformed(evt);
            }
        });
        getContentPane().add(txtQueixas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 260, 110));
        getContentPane().add(txtSintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 260, 120));
        getContentPane().add(txtCondicoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 260, 110));

        lblQueixas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblQueixas.setText("Queixas");
        getContentPane().add(lblQueixas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblSintomas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSintomas.setText("Sintomas");
        getContentPane().add(lblSintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        lblCondicoes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCondicoes.setText("Condições");
        getContentPane().add(lblCondicoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQueixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueixasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueixasActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            int pacienteId = Integer.parseInt(txtPaciente.getText());
            String queixas = txtQueixas.getText();
            String sintomas = txtSintomas.getText();
            String condicoes = txtCondicoes.getText();

            // Verificação básica de campos obrigatórios
            if (queixas.isEmpty() || sintomas.isEmpty() || condicoes.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
            }
            
            // Criação da Anamnese
            Anamnese anamnese = new Anamnese();
            anamnese.setQueixas(queixas);
            anamnese.setSintomas(sintomas);
            anamnese.setCondicoes(condicoes);
        
            // Criação do Prontuário e associação do paciente e anamnese
            Prontuario prontuario = new Prontuario();
            //prontuario.setPaciente(paciente);        // Associação com o paciente
            prontuario.getAnamneses();                  // Adiciona a anamnese
        
            prontuarioController.save(prontuario);
        
            JOptionPane.showMessageDialog(this, "Prontuário salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            // Limpar campos após salvar
            txtPaciente.setText("");
            txtQueixas.setText("");
            txtSintomas.setText("");
            txtCondicoes.setText("");
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID do paciente inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar o prontuário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarProntuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCondicoes;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblQueixas;
    private javax.swing.JLabel lblSintomas;
    private javax.swing.JTextField txtCondicoes;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JTextField txtQueixas;
    private javax.swing.JTextField txtSintomas;
    // End of variables declaration//GEN-END:variables
}
