/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prontuario.view;

import br.com.ifba.Prg03sgsApplication;
import br.com.ifba.paciente.entity.Paciente;
import br.com.ifba.prontuario.controller.ProntuarioIController;
import br.com.ifba.prontuario.entity.Prontuario;
import jakarta.annotation.PostConstruct;
import jakarta.persistence.Entity;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author Glauber
 */
@Component
public class TelaProntuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaProntuario
     */
    
    @Autowired
    private ProntuarioIController prontuarioController;
    
    private ApplicationContext context;
    
    public TelaProntuario() {
        initComponents();
    }
    
    @PostConstruct
    public void init() {
        mostrarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        btnAbrir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProntuario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Prontuario");
        getContentPane().add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        btnAbrir.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 150, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 10, -1));

        tblProntuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProntuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
        // Obtendo a linha selecionada na tabela
    int linhaSelecionada = tblProntuario.getSelectedRow();
     Paciente paciente = new Paciente();
    if (linhaSelecionada != -1) {
        long idPaciente = (long) tblProntuario.getValueAt(linhaSelecionada, 0);
        
        // Buscar paciente pelo ID no banco de dados
        //Paciente paciente = prontuarioController.findById(idPaciente);

        // Verifica se o paciente foi encontrado
        if (paciente != null) {
            JOptionPane.showMessageDialog(this, 
                "Paciente Encontrado:\n" +
                "ID: " + paciente.getId() + "\n" +
                "Nome: " + paciente.getNome() + "\n" +
                "CPF: " + paciente.getCpf() + "\n" +
                "Sexo: " + paciente.getSexo() + "\n" +
                "Data de Nascimento: " + paciente.getDataNascimento() + "\n" +
                "Endereço: " + paciente.getEndereco() + "\n" +
                "Contato: " + paciente.getContato() + "\n");
    } else {
        JOptionPane.showMessageDialog(this, "Paciente não encontrado.");
    }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um paciente para abrir.");
    }

    }//GEN-LAST:event_btnAbrirActionPerformed
    
    private void mostrarTabela () {
  
        List<Prontuario> prontuarios = prontuarioController.findAll();
   
        DefaultTableModel tableModel = (DefaultTableModel) tblProntuario.getModel();
        tableModel.setRowCount(0);

        // Adiciona os cursos à tabela
        for (Prontuario prontuario : prontuarios) {
            tableModel.addRow(new Object[]{
            prontuario.getId(),
            prontuario.getDataCriacao(),
            prontuario.getPaciente(),
            prontuario.getAnamneses(),
            });
        }
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProntuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblProntuario;
    // End of variables declaration//GEN-END:variables
}
