/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.funcionarios.view;

import br.com.ifba.funcionarios.controller.FuncionariosIController;
import br.com.ifba.funcionarios.entity.Funcionarios;
import jakarta.annotation.PostConstruct;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Rafael
 */
@Component
public class TelaEditarFuncionarios extends javax.swing.JFrame {
    
    @Autowired
    private FuncionariosIController funcionariosController;
    /**
     * Creates new form TelaEditarFuncionarios
     */
    public TelaEditarFuncionarios() {
        initComponents();
    }
    
    @PostConstruct
    public void init() {
        mostrarTabela();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditarTelaFuncionario = new javax.swing.JButton();
        txtEditNome = new javax.swing.JTextField();
        lblEditarFuncionario1 = new javax.swing.JLabel();
        lblEditarFuncionario2 = new javax.swing.JLabel();
        txtEditCpf = new javax.swing.JTextField();
        lblEditarFuncionario3 = new javax.swing.JLabel();
        txtEditTelefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditar = new javax.swing.JTable();
        lblEditarFuncionario4 = new javax.swing.JLabel();
        txtEditAniversario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarTelaFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEditarTelaFuncionario.setText("Editar");
        btnEditarTelaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTelaFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarTelaFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));
        getContentPane().add(txtEditNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 40, 170, -1));

        lblEditarFuncionario1.setText("Digite o nome do funcionario q deseja editar:");
        getContentPane().add(lblEditarFuncionario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, -1, -1));

        lblEditarFuncionario2.setText("Digite o Cpf do funcionario q deseja editar:");
        getContentPane().add(lblEditarFuncionario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 80, -1, -1));
        getContentPane().add(txtEditCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 114, 170, -1));

        lblEditarFuncionario3.setText("Digite o Telefone do funcionario q deseja editar:");
        getContentPane().add(lblEditarFuncionario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 154, -1, -1));
        getContentPane().add(txtEditTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 188, 170, -1));

        tblEditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Cpf", "Telefone", "Data de aniversario", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEditar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 443, 224));

        lblEditarFuncionario4.setText("Digite a data de aniversario do funcionario q deseja editar:");
        getContentPane().add(lblEditarFuncionario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        getContentPane().add(txtEditAniversario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarTelaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTelaFuncionarioActionPerformed
                                          
        int linhaSelecionada = tblEditar.getSelectedRow();
        if (linhaSelecionada != -1) {

            long idFuncionario;
            
            Object valor = tblEditar.getValueAt(linhaSelecionada, 0); // Obtém o valor da célula

            if (valor instanceof Number) { 
                idFuncionario = ((Number) valor).longValue(); // Se já for um número, converte corretamente
            } else {
                idFuncionario = Long.parseLong(valor.toString()); // Se for String, converte para long
}
        
            Funcionarios funcionario = funcionariosController.findById(idFuncionario);
        

            funcionario.setNome(txtEditNome.getText());
            funcionario.setCpf(txtEditCpf.getText());
            funcionario.setTelefone(txtEditTelefone.getText());
            funcionario.setDataNascimento(txtEditAniversario.getText());
            
            funcionariosController.update(funcionario);
            
            JOptionPane.showMessageDialog(this, "Atualizado com sucesso.");
        } else {
        
            JOptionPane.showMessageDialog(this, "Selecione um funcionario na tabela para editar.");
        }
    }//GEN-LAST:event_btnEditarTelaFuncionarioActionPerformed
    
    private void mostrarTabela () {
        
        List<Funcionarios> funcionarios = funcionariosController.findAll();
   
        DefaultTableModel tableModel = (DefaultTableModel) tblEditar.getModel();
        tableModel.setRowCount(0);

        // Adiciona os funcionarios à tabela
        for (Funcionarios funcionario : funcionarios) {
            tableModel.addRow(new Object[]{
            funcionario.getNome(),
            funcionario.getCpf(),
            funcionario.getTelefone(),
            funcionario.getId(),
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarTelaFuncionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditarFuncionario1;
    private javax.swing.JLabel lblEditarFuncionario2;
    private javax.swing.JLabel lblEditarFuncionario3;
    private javax.swing.JLabel lblEditarFuncionario4;
    private javax.swing.JTable tblEditar;
    private javax.swing.JTextField txtEditAniversario;
    private javax.swing.JTextField txtEditCpf;
    private javax.swing.JTextField txtEditNome;
    private javax.swing.JTextField txtEditTelefone;
    // End of variables declaration//GEN-END:variables
}
