/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.funcionarios.view;

import br.com.ifba.funcionarios.controller.FuncionariosIController;
import br.com.ifba.funcionarios.entity.Funcionarios;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Rafael
 */
@Component
public class TelaAdicionarFuncionario extends javax.swing.JFrame {
    
    @Autowired
    private FuncionariosIController funcionariosController;
    /**
     * Creates new form TelaAdicionarFuncionario
     */
    public TelaAdicionarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDigiteFuncionario1 = new javax.swing.JLabel();
        txtFuncionarioAdd1 = new javax.swing.JTextField();
        btnAdicionarTelaFuncionario = new javax.swing.JButton();
        txtFuncionarioAdd = new javax.swing.JTextField();
        lblDigiteFuncionario = new javax.swing.JLabel();
        lblCpfFuncionario = new javax.swing.JLabel();
        txtCpfAdd = new javax.swing.JTextField();
        lblTelefoneFuncionario = new javax.swing.JLabel();
        txtTelefoneAdd = new javax.swing.JTextField();
        txtAddEmail = new javax.swing.JTextField();
        lblDigiteEmail = new javax.swing.JLabel();
        txtAddCargo = new javax.swing.JTextField();
        lblDigiteCargo = new javax.swing.JLabel();
        txtAddSalario = new javax.swing.JTextField();
        lblDigiteSalario = new javax.swing.JLabel();
        txtAddEndereco = new javax.swing.JTextField();
        lblDigiteEndereco = new javax.swing.JLabel();
        txtAddNascimento = new javax.swing.JTextField();
        lblDigiteNascimento = new javax.swing.JLabel();

        lblDigiteFuncionario1.setText("Digite o nome do funcionario q deseja adicionar:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdicionarTelaFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAdicionarTelaFuncionario.setText("Adicionar");
        btnAdicionarTelaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTelaFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionarTelaFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, -1, -1));
        getContentPane().add(txtFuncionarioAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 59, 167, -1));

        lblDigiteFuncionario.setText("Digite o Nome do funcionario q deseja adicionar:");
        getContentPane().add(lblDigiteFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, -1, -1));

        lblCpfFuncionario.setText("Digite o Cpf do funcionario q deseja adicionar:");
        getContentPane().add(lblCpfFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 99, -1, -1));
        getContentPane().add(txtCpfAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 133, 169, -1));

        lblTelefoneFuncionario.setText("Digite o Telefone do funcionario q deseja adicionar:");
        getContentPane().add(lblTelefoneFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 183, -1, -1));
        getContentPane().add(txtTelefoneAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 217, 169, -1));
        getContentPane().add(txtAddEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 167, -1));

        lblDigiteEmail.setText("Digite o Email do funcionario q deseja adicionar:");
        getContentPane().add(lblDigiteEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        getContentPane().add(txtAddCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 167, -1));

        lblDigiteCargo.setText("Digite o Cargo do funcionario q deseja adicionar:");
        getContentPane().add(lblDigiteCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        getContentPane().add(txtAddSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 167, -1));

        lblDigiteSalario.setText("Digite o Salario do funcionario q deseja adicionar:");
        getContentPane().add(lblDigiteSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));
        getContentPane().add(txtAddEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 167, 20));

        lblDigiteEndereco.setText("Digite o Endereço do funcionario q deseja adicionar:");
        getContentPane().add(lblDigiteEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, 20));
        getContentPane().add(txtAddNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 167, -1));

        lblDigiteNascimento.setText("Digite a Data de nascimento do funcionario q deseja adicionar:");
        getContentPane().add(lblDigiteNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarTelaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTelaFuncionarioActionPerformed
        
            String nome = txtFuncionarioAdd.getText();
            String cpf = txtCpfAdd.getText();
            String telefone = txtTelefoneAdd.getText();
            String nascimento = txtAddNascimento.getText();
            String endereco = txtAddEndereco.getText();
            String email = txtAddEmail.getText();
            String cargo = txtAddCargo.getText();
            String salario = txtAddSalario.getText();
            

            // Verificação básica de campos obrigatórios
            if (nome.isEmpty() || cpf.isEmpty() || telefone.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatorios", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Funcionarios funcionario = new Funcionarios();
            funcionario.setNome(nome);
            funcionario.setCpf(cpf);
            funcionario.setTelefone(telefone);
            funcionario.setEmail(email);
            funcionario.setDataNascimento(nascimento);
            funcionario.setEndereco(endereco);
            funcionario.setCargo(cargo);

            funcionariosController.save(funcionario);

            JOptionPane.showMessageDialog(this, "Funcionario salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            // Limpa os campos após salvar
            txtFuncionarioAdd.setText("");
            txtCpfAdd.setText("");
            txtTelefoneAdd.setText("");
            txtAddEmail.setText("");

    }//GEN-LAST:event_btnAdicionarTelaFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarTelaFuncionario;
    private javax.swing.JLabel lblCpfFuncionario;
    private javax.swing.JLabel lblDigiteCargo;
    private javax.swing.JLabel lblDigiteEmail;
    private javax.swing.JLabel lblDigiteEndereco;
    private javax.swing.JLabel lblDigiteFuncionario;
    private javax.swing.JLabel lblDigiteFuncionario1;
    private javax.swing.JLabel lblDigiteNascimento;
    private javax.swing.JLabel lblDigiteSalario;
    private javax.swing.JLabel lblTelefoneFuncionario;
    private javax.swing.JTextField txtAddCargo;
    private javax.swing.JTextField txtAddEmail;
    private javax.swing.JTextField txtAddEndereco;
    private javax.swing.JTextField txtAddNascimento;
    private javax.swing.JTextField txtAddSalario;
    private javax.swing.JTextField txtCpfAdd;
    private javax.swing.JTextField txtFuncionarioAdd;
    private javax.swing.JTextField txtFuncionarioAdd1;
    private javax.swing.JTextField txtTelefoneAdd;
    // End of variables declaration//GEN-END:variables
}
