/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.medicamento.view;

import javax.swing.table.DefaultTableModel;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import br.com.ifba.medicamento.controller.MedicamentoIController;
import br.com.ifba.medicamento.entity.Medicamento;
import jakarta.annotation.PostConstruct;
import java.awt.GraphicsEnvironment;
import java.util.List;
import org.springframework.context.annotation.Lazy;
/**
 *
 * @author rober
 */
@Component
@Lazy
@RequiredArgsConstructor
public class TelaMedicamento extends javax.swing.JFrame {

    private final DefaultTableModel tabela = new DefaultTableModel(new Object[]{"ID", "Nome", "Categoria", "Data de Validade", "Quantidade"}, 0);
    
    private final MedicamentoIController medicamentoController;
    
    private int linhaSelecionada = 0;
    
    {
        initComponents();
    }
    
    @PostConstruct
    private void init () {
        if (!GraphicsEnvironment.isHeadless()) {
            initTable();
        }
    }
    
    private void initTable () {
        List<Medicamento> medicamentos = medicamentoController.findAll();
        for (Medicamento medicamento : medicamentos) {
            tabela.addRow(new Object[]{medicamento.getId(), medicamento.getNome(), 
                medicamento.getCategoria(), medicamento.getDataValidade(), medicamento.getQuantidade()});
        }
        tableMedicamento.setModel(tabela);
    }
    
    public void updateTable() {
        tabela.setRowCount(0);
        List<Medicamento> medicamentos = medicamentoController.findAll();
        for (Medicamento medicamento : medicamentos) {
            tabela.addRow(new Object[]{medicamento.getId(), medicamento.getNome(), 
                medicamento.getCategoria(), medicamento.getDataValidade(), medicamento.getQuantidade()});
        }
        tableMedicamento.setModel(tabela);
    }
    
    public void updataTableBySearchNome(String nome) {
        List<Medicamento> medicamentos = medicamentoController.findByNomeLikeIgnoreCase(nome);
        
        if (medicamentos != null) {
            tabela.setRowCount(0);
            for (Medicamento medicamento : medicamentos) {
                tabela.addRow(new Object[]{medicamento.getId(), medicamento.getNome(), 
                    medicamento.getCategoria(), medicamento.getDataValidade(), medicamento.getQuantidade()});
            }
            tableMedicamento.setModel(tabela);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLinhaSelecionada = new javax.swing.JLabel();
        txtNomeMedicamento = new javax.swing.JTextField();
        lblTextoNomeMedicamento = new javax.swing.JLabel();
        lblTextoLinhaSelecionada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMedicamento = new javax.swing.JTable();
        lblTituloMedicamento = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblLinhaSelecionada.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblLinhaSelecionada.setText("0");

        txtNomeMedicamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblTextoNomeMedicamento.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTextoNomeMedicamento.setText("Informe o nome do Medicamento");

        lblTextoLinhaSelecionada.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblTextoLinhaSelecionada.setText("Linha Selecionada");

        tableMedicamento.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tableMedicamento.setModel(tabela);
        jScrollPane1.setViewportView(tableMedicamento);

        lblTituloMedicamento.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTituloMedicamento.setText("MEDICAMENTOS");

        btnAdicionar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");

        btnEditar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEditar.setText("Editar");

        btnRemover.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnRemover.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTextoNomeMedicamento)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTextoLinhaSelecionada)
                        .addGap(18, 18, 18)
                        .addComponent(lblLinhaSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(lblTituloMedicamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTituloMedicamento)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextoNomeMedicamento)
                            .addComponent(txtNomeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextoLinhaSelecionada)
                            .addComponent(lblLinhaSelecionada))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnAdicionar)
                        .addGap(67, 67, 67)
                        .addComponent(btnRemover)
                        .addGap(66, 66, 66)
                        .addComponent(btnEditar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedicamentoIController medicamentoController = null;
                TelaMedicamento telaMedicamento = new TelaMedicamento(medicamentoController);
                telaMedicamento.setVisible(true);
                telaMedicamento.init();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLinhaSelecionada;
    private javax.swing.JLabel lblTextoLinhaSelecionada;
    private javax.swing.JLabel lblTextoNomeMedicamento;
    private javax.swing.JLabel lblTituloMedicamento;
    private javax.swing.JTable tableMedicamento;
    private javax.swing.JTextField txtNomeMedicamento;
    // End of variables declaration//GEN-END:variables
}
