/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.visita.view;

import br.com.ifba.visita.controller.VisitaIController;
import br.com.ifba.visita.entity.Visita;
import jakarta.annotation.PostConstruct;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author sunhe
 */

@Component
@RequiredArgsConstructor
public class TelaCadastrarVisita extends javax.swing.JFrame {

    private TelaVisitas telaVisitas;
    @Autowired
    private final VisitaIController visitaController;
    
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfoCadastro = new javax.swing.JLabel();
        btnEnviaCadastro = new javax.swing.JButton();
        lblInfoNomeDigitador = new javax.swing.JLabel();
        lblDataVisita = new javax.swing.JLabel();
        txtNomeDigitador = new javax.swing.JTextField();
        txtDataVisita = new javax.swing.JTextField();
        lblConferidoPor = new javax.swing.JLabel();
        txtConferidoPor = new javax.swing.JTextField();
        lblNumFolha = new javax.swing.JLabel();
        txtNumFolha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 255, 204));

        lblInfoCadastro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblInfoCadastro.setText("CADASTRAR VISITA");
        lblInfoCadastro.setToolTipText("");

        btnEnviaCadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnviaCadastro.setText("CADASTRAR");
        btnEnviaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviaCadastroActionPerformed(evt);
            }
        });

        lblInfoNomeDigitador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInfoNomeDigitador.setText("Digitado por:");

        lblDataVisita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataVisita.setText("Data da Visita:");

        txtNomeDigitador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDigitadorActionPerformed(evt);
            }
        });

        txtDataVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataVisitaActionPerformed(evt);
            }
        });

        lblConferidoPor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConferidoPor.setText("Conferido Por: ");

        txtConferidoPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConferidoPorActionPerformed(evt);
            }
        });

        lblNumFolha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumFolha.setText("Número da Folha:");

        txtNumFolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFolhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblInfoNomeDigitador)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNomeDigitador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNumFolha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumFolha, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(btnEnviaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblConferidoPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConferidoPor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblDataVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInfoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblInfoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoNomeDigitador)
                    .addComponent(txtNomeDigitador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataVisita)
                    .addComponent(txtDataVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConferidoPor)
                    .addComponent(txtConferidoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumFolha)
                    .addComponent(txtNumFolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnEnviaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviaCadastroActionPerformed
        // TODO add your handling code here:
     
        Visita visita = new Visita();
        String digitadoPor = txtNomeDigitador.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String dataVisita = txtDataVisita.getText();
        String conferidoPor = txtConferidoPor.getText();
        int numeroFolha = Integer.parseInt(txtNumFolha.getText());
        
        if(digitadoPor.isEmpty() || conferidoPor.isEmpty()){
            JOptionPane.showMessageDialog(this, "Campos obrigatórios não preenchidos!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            visita.setDigitadoPor(digitadoPor);
            visita.setDataVisita(LocalDate.parse(dataVisita, formatter));
            visita.setConferidoPor(conferidoPor);
            visita.setNumeroFicha(numeroFolha);
            
            visitaController.save(visita);
            JOptionPane.showMessageDialog(this, "Visita salva com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            telaVisitas.listarTabela();
            this.dispose();
        }

    }//GEN-LAST:event_btnEnviaCadastroActionPerformed

    private void txtNomeDigitadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDigitadorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomeDigitadorActionPerformed

    private void txtDataVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataVisitaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDataVisitaActionPerformed

    private void txtConferidoPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConferidoPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConferidoPorActionPerformed

    private void txtNumFolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFolhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFolhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarVisita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarVisita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarVisita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarVisita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisitaIController visitaController = null;
                TelaCadastrarVisita telaVis = new TelaCadastrarVisita(visitaController);
                telaVis.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviaCadastro;
    private javax.swing.JLabel lblConferidoPor;
    private javax.swing.JLabel lblDataVisita;
    private javax.swing.JLabel lblInfoCadastro;
    private javax.swing.JLabel lblInfoNomeDigitador;
    private javax.swing.JLabel lblNumFolha;
    private javax.swing.JTextField txtConferidoPor;
    private javax.swing.JTextField txtDataVisita;
    private javax.swing.JTextField txtNomeDigitador;
    private javax.swing.JTextField txtNumFolha;
    // End of variables declaration//GEN-END:variables
}
