/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.visita.view;

import br.com.ifba.Prg03sgsApplication;
import br.com.ifba.fichavisita.view.TelaCadastrarFicha;
import br.com.ifba.visita.controller.VisitaIController;
import br.com.ifba.visita.entity.Visita;
import jakarta.annotation.PostConstruct;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author sunhe
 */

@Component
public class TelaVisitas extends javax.swing.JFrame {

    @Autowired
    private VisitaIController visitaController;
    
    private ApplicationContext context;
    
    public TelaVisitas() {
        initComponents();
    }
    
    @PostConstruct
    public void init() {
        listarTabela();
    }
    
    public void listarTabela() {
  
        List<Visita> visitas = visitaController.findAll();
   
        DefaultTableModel tableModel = (DefaultTableModel) tblVisitas.getModel();
        tableModel.setRowCount(0);

        for(Visita visita : visitas) {
            tableModel.addRow(new Object[]{
            visita.getDigitadoPor(),
            visita.getDataVisita(),
            visita.getConferidoPor(),
            visita.getNumeroFicha()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPegaBusca = new javax.swing.JTextField();
        btnCadastrarVisita = new javax.swing.JButton();
        btnEditarVisita = new javax.swing.JButton();
        btnRemoverVisita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisitas = new javax.swing.JTable();
        btnCadastrarFichaVisita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPegaBusca.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtPegaBusca.setText("      pesquisar");
        txtPegaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPegaBuscaActionPerformed(evt);
            }
        });

        btnCadastrarVisita.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCadastrarVisita.setText("CADASTRAR VISITA");
        btnCadastrarVisita.setBorder(null);
        btnCadastrarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVisitaActionPerformed(evt);
            }
        });

        btnEditarVisita.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEditarVisita.setText("EDITAR VISITA");
        btnEditarVisita.setBorder(null);
        btnEditarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarVisitaActionPerformed(evt);
            }
        });

        btnRemoverVisita.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRemoverVisita.setText("APAGAR VISITA");
        btnRemoverVisita.setBorder(null);
        btnRemoverVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverVisitaActionPerformed(evt);
            }
        });

        tblVisitas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblVisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DIGITADO POR", "DATA", "CONFERIDO POR", "NÚMERO DA FOLHA"
            }
        ));
        jScrollPane1.setViewportView(tblVisitas);

        btnCadastrarFichaVisita.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnCadastrarFichaVisita.setText("CADASTRAR FICHA");
        btnCadastrarFichaVisita.setBorder(null);
        btnCadastrarFichaVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFichaVisitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPegaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrarFichaVisita, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPegaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarFichaVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPegaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPegaBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPegaBuscaActionPerformed

    private void btnCadastrarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVisitaActionPerformed
        // TODO add your handling code here:
        ConfigurableApplicationContext context = (ConfigurableApplicationContext) 
            SpringApplication.run(Prg03sgsApplication.class);
        
        TelaCadastrarVisita telaCadastrarVi = context.getBean(TelaCadastrarVisita.class);
        telaCadastrarVi.setDefaultCloseOperation(TelaVisitas.DISPOSE_ON_CLOSE);
        telaCadastrarVi.setVisible(true);
    }//GEN-LAST:event_btnCadastrarVisitaActionPerformed

    private void btnEditarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarVisitaActionPerformed
        // TODO add your handling code here:
        ConfigurableApplicationContext context = (ConfigurableApplicationContext) 
            SpringApplication.run(Prg03sgsApplication.class);
        
        TelaEditarVisita telaEditarVi = context.getBean(TelaEditarVisita.class);
        telaEditarVi.setDefaultCloseOperation(TelaVisitas.DISPOSE_ON_CLOSE);
        telaEditarVi.setVisible(true);
       
    }//GEN-LAST:event_btnEditarVisitaActionPerformed

    private void btnRemoverVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverVisitaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRemoverVisitaActionPerformed

    //Botão para chamar a tela de cadastrar uma ficha.
    private void btnCadastrarFichaVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFichaVisitaActionPerformed
        // TODO add your handling code here:
        ConfigurableApplicationContext context = (ConfigurableApplicationContext) 
            SpringApplication.run(Prg03sgsApplication.class);
        
        TelaCadastrarFicha telaCadFicha = context.getBean(TelaCadastrarFicha.class);
        telaCadFicha.setDefaultCloseOperation(TelaVisitas.DISPOSE_ON_CLOSE);
        telaCadFicha.setVisible(true);
        
    }//GEN-LAST:event_btnCadastrarFichaVisitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVisitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFichaVisita;
    private javax.swing.JButton btnCadastrarVisita;
    private javax.swing.JButton btnEditarVisita;
    private javax.swing.JButton btnRemoverVisita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVisitas;
    private javax.swing.JTextField txtPegaBusca;
    // End of variables declaration//GEN-END:variables
}
