/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atendimento.view;

import br.com.ifba.anamnese.entity.Anamnese;
import br.com.ifba.atendimento.controller.AtendimentoIController;
import br.com.ifba.atendimento.entity.Atendimento;
import br.com.ifba.funcionarios.controller.FuncionariosIController;
import br.com.ifba.funcionarios.entity.Funcionarios;
import br.com.ifba.paciente.controller.PacienteIController;
import br.com.ifba.paciente.entity.Paciente;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author larissa
 */

@Component
public class TelaCadastrarAtendimento extends javax.swing.JFrame {
    
    private TelaAtendimento telaAtendimento;
    @Autowired
    private AtendimentoIController atendimentoController;
    
    @Autowired
    private FuncionariosIController funcionarioController;
    
    @Autowired
    private PacienteIController pacienteController;

    /**
     * Creates new form TelaCadastrarAtendimento
     * @param telaAtendimento
     */
    public TelaCadastrarAtendimento(TelaAtendimento telaAtendimento) {
        this.telaAtendimento = telaAtendimento;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCpfFuncionario = new javax.swing.JLabel();
        lblCpfPaciente = new javax.swing.JLabel();
        lblTipoAtendimento = new javax.swing.JLabel();
        lblDataHoraInicio = new javax.swing.JLabel();
        lblDataHoraFim = new javax.swing.JLabel();
        txtCpfFuncionario = new javax.swing.JTextField();
        txtCpfPaciente = new javax.swing.JTextField();
        txtDataHoraFim = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        txtTipoAtendimento = new javax.swing.JTextField();
        txtDataHoraInicio = new javax.swing.JTextField();
        lblFormatoDataHoraInicio = new javax.swing.JLabel();
        lblFormatoDataHoraFim = new javax.swing.JLabel();
        lblQueixas = new javax.swing.JLabel();
        lblCondicoes = new javax.swing.JLabel();
        scrollPaneCondicoes = new javax.swing.JScrollPane();
        txtCondicoes = new javax.swing.JTextArea();
        scrollPaneQueixas = new javax.swing.JScrollPane();
        txtQueixas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGS - Tela de Cadastro de Atendimentos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCpfFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCpfFuncionario.setText("CPF do funcionário:");
        getContentPane().add(lblCpfFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 160, -1));

        lblCpfPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCpfPaciente.setText("CPF do paciente:");
        getContentPane().add(lblCpfPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, -1));

        lblTipoAtendimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipoAtendimento.setText("Tipo de atendimento:");
        getContentPane().add(lblTipoAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 180, -1));

        lblDataHoraInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataHoraInicio.setText("Data e hora de início:");
        getContentPane().add(lblDataHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 180, -1));

        lblDataHoraFim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataHoraFim.setText("Data e hora de término:");
        getContentPane().add(lblDataHoraFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 200, -1));
        getContentPane().add(txtCpfFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 280, 30));
        getContentPane().add(txtCpfPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 280, 30));
        getContentPane().add(txtDataHoraFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 280, 30));

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 120, 50));
        getContentPane().add(txtTipoAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 280, 30));
        getContentPane().add(txtDataHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 280, 30));

        lblFormatoDataHoraInicio.setForeground(new java.awt.Color(153, 153, 153));
        lblFormatoDataHoraInicio.setText("dd/MM/yyyy HH:mm");
        getContentPane().add(lblFormatoDataHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 120, -1));

        lblFormatoDataHoraFim.setForeground(new java.awt.Color(153, 153, 153));
        lblFormatoDataHoraFim.setText("dd/MM/yyyy HH:mm");
        getContentPane().add(lblFormatoDataHoraFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 120, -1));

        lblQueixas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQueixas.setText("Queixas:");
        getContentPane().add(lblQueixas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 70, -1));

        lblCondicoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCondicoes.setText("Condição física:");
        getContentPane().add(lblCondicoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 130, -1));

        txtCondicoes.setColumns(20);
        txtCondicoes.setRows(5);
        scrollPaneCondicoes.setViewportView(txtCondicoes);

        getContentPane().add(scrollPaneCondicoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 280, -1));

        txtQueixas.setColumns(20);
        txtQueixas.setRows(5);
        scrollPaneQueixas.setViewportView(txtQueixas);

        getContentPane().add(scrollPaneQueixas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 280, -1));

        setSize(new java.awt.Dimension(614, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // Salvando as informações da tela em variáveis
        String cpfFuncionario = txtCpfFuncionario.getText();
        String cpfPaciente = txtCpfPaciente.getText();
        String tipoAtendimento = txtTipoAtendimento.getText();
        LocalDateTime dataHoraInicio = LocalDateTime.parse(txtDataHoraInicio.getText(), 
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
        LocalDateTime dataHoraFim = LocalDateTime.parse(txtDataHoraFim.getText(), 
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
        
        Anamnese anamnese = new Anamnese();
        anamnese.setQueixas(txtQueixas.getText());
        anamnese.setCondicoes(txtCondicoes.getText());
        
        if(dataHoraInicio.isAfter(dataHoraFim)) {
            JOptionPane.showMessageDialog(
                    null,
                    "Insira data e hora de início anterior à data e hora de término.\n"
            );
        } else if(funcionarioController.findByCpf(cpfFuncionario) == null) {
            JOptionPane.showMessageDialog(
                    null, 
                    "Não existe funcionário com esse CPF.\n"
            );
        } else if(pacienteController.findByCpf(cpfPaciente) == null) {
            JOptionPane.showMessageDialog(
                    null, 
                    "Não existe paciente com esse CPF.\n"
            );
        } else {
            
            Funcionarios funcionario = funcionarioController.findByCpf(cpfFuncionario);
            Paciente paciente = pacienteController.findByCpf(cpfPaciente);
            
            //Insere as informações no atendimento
            Atendimento atendimento = new Atendimento();
            atendimento.setAnamnese(anamnese);
            atendimento.setFuncionario(funcionario);
            atendimento.setPaciente(paciente);
            atendimento.setTipoAtendimento(tipoAtendimento);
            atendimento.setDataHoraInicio(dataHoraInicio);
            atendimento.setDataHoraFim(dataHoraFim);

            //Salva o novo atendimento
            atendimentoController.save(atendimento);

            //Fecha a tela de cadastro e carrega a tabela da tela de atendimento novamente
            telaAtendimento.carregarTabela();
            this.dispose();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaCadastrarAtendimento().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel lblCondicoes;
    private javax.swing.JLabel lblCpfFuncionario;
    private javax.swing.JLabel lblCpfPaciente;
    private javax.swing.JLabel lblDataHoraFim;
    private javax.swing.JLabel lblDataHoraInicio;
    private javax.swing.JLabel lblFormatoDataHoraFim;
    private javax.swing.JLabel lblFormatoDataHoraInicio;
    private javax.swing.JLabel lblQueixas;
    private javax.swing.JLabel lblTipoAtendimento;
    private javax.swing.JScrollPane scrollPaneCondicoes;
    private javax.swing.JScrollPane scrollPaneQueixas;
    private javax.swing.JTextArea txtCondicoes;
    private javax.swing.JTextField txtCpfFuncionario;
    private javax.swing.JTextField txtCpfPaciente;
    private javax.swing.JTextField txtDataHoraFim;
    private javax.swing.JTextField txtDataHoraInicio;
    private javax.swing.JTextArea txtQueixas;
    private javax.swing.JTextField txtTipoAtendimento;
    // End of variables declaration//GEN-END:variables
}
