/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atendimento.view;

import br.com.ifba.atendimento.controller.AtendimentoIController;
import br.com.ifba.atendimento.entity.Atendimento;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author larissa
 */

@Component
public class TelaCadastrarAtendimento extends javax.swing.JFrame {
    
    private TelaAtendimento telaAtendimento;
    @Autowired
    private AtendimentoIController atendimentoController;

    /**
     * Creates new form TelaCadastrarAtendimento
     */
    public TelaCadastrarAtendimento(TelaAtendimento telaAtendimento) {
        this.telaAtendimento = telaAtendimento;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeFuncionario = new javax.swing.JLabel();
        lblNomePaciente = new javax.swing.JLabel();
        lblTipoAtendimento = new javax.swing.JLabel();
        lblDataHoraInicio = new javax.swing.JLabel();
        lblDataHoraFim = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtNomePaciente = new javax.swing.JTextField();
        txtDataHoraFim = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        txtTipoAtendimento = new javax.swing.JTextField();
        txtDataHoraInicio = new javax.swing.JTextField();
        lblFormatoDataHoraInicio = new javax.swing.JLabel();
        lblFormatoDataHoraFim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGS - Tela de Cadastro de Atendimentos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeFuncionario.setText("Nome do funcionário:");
        getContentPane().add(lblNomeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 180, -1));

        lblNomePaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomePaciente.setText("Nome do paciente:");
        getContentPane().add(lblNomePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 160, -1));

        lblTipoAtendimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipoAtendimento.setText("Tipo de atendimento:");
        getContentPane().add(lblTipoAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 180, -1));

        lblDataHoraInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataHoraInicio.setText("Data e hora de início:");
        getContentPane().add(lblDataHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 180, -1));

        lblDataHoraFim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataHoraFim.setText("Data e hora de término:");
        getContentPane().add(lblDataHoraFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, -1));
        getContentPane().add(txtNomeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 280, 30));
        getContentPane().add(txtNomePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 280, 30));
        getContentPane().add(txtDataHoraFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 280, 30));

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 120, 50));
        getContentPane().add(txtTipoAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 280, 30));
        getContentPane().add(txtDataHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 280, 30));

        lblFormatoDataHoraInicio.setForeground(new java.awt.Color(153, 153, 153));
        lblFormatoDataHoraInicio.setText("dd/MM/yyyy HH:mm");
        getContentPane().add(lblFormatoDataHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 120, -1));

        lblFormatoDataHoraFim.setForeground(new java.awt.Color(153, 153, 153));
        lblFormatoDataHoraFim.setText("dd/MM/yyyy HH:mm");
        getContentPane().add(lblFormatoDataHoraFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 120, -1));

        setSize(new java.awt.Dimension(614, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // Salvando as informações da tela em variáveis
        String nomeFuncionario = txtNomeFuncionario.getText();
        String nomePaciente = txtNomePaciente.getText();
        String tipoAtendimento = txtTipoAtendimento.getText();
        LocalDateTime dataHoraInicio = LocalDateTime.parse(txtDataHoraInicio.getText(), 
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
        LocalDateTime dataHoraFim = LocalDateTime.parse(txtDataHoraFim.getText(), 
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
        
        if(dataHoraInicio.isAfter(dataHoraFim)) {
            JOptionPane.showMessageDialog(
                    null, 
                    "Insira data e hora de início anterior à data e hora de término.\n"
            );
        } else {
            //A verificação de funcionário e paciente só poderá ser feita após a criação dos CRUDs dessas entidades
            //Insere as informações no atendimento
            Atendimento atendimento = new Atendimento();
            atendimento.setNomeFuncionario(nomeFuncionario);
            atendimento.setIdFuncionario(6L);
            atendimento.setNomePaciente(nomePaciente);
            atendimento.setIdPaciente(3L);
            atendimento.setTipoAtendimento(tipoAtendimento);
            atendimento.setDataHoraInicio(dataHoraInicio);
            atendimento.setDataHoraFim(dataHoraFim);

            //Salva o novo atendimento
            atendimentoController.save(atendimento);

            //Fecha a tela de cadastro e carrega a tabela da tela de atendimento novamente
            telaAtendimento.carregarTabela();
            this.dispose();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaCadastrarAtendimento().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel lblDataHoraFim;
    private javax.swing.JLabel lblDataHoraInicio;
    private javax.swing.JLabel lblFormatoDataHoraFim;
    private javax.swing.JLabel lblFormatoDataHoraInicio;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblTipoAtendimento;
    private javax.swing.JTextField txtDataHoraFim;
    private javax.swing.JTextField txtDataHoraInicio;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtTipoAtendimento;
    // End of variables declaration//GEN-END:variables
}
