/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.usuario.view;

import br.com.ifba.perfilusuario.entity.PerfilUsuario;
import br.com.ifba.usuario.controller.UsuarioIController;
import br.com.ifba.usuario.entity.Usuario;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 *
 * @author valdo
 */
@Component
@RequiredArgsConstructor
public class TelaCriarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionarUsuario
     */
    private TelaUsuario telaUsuario;
    private final UsuarioIController usuarioController;
    
    //Inicia os componentes visuais.
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    //Vincula a TelaUsuario a esta, possibilitando que a tabela seja atualizada automaticamente após a criação de um usuário.
    public void vincularTela(TelaUsuario telaUsuario) {
        this.telaUsuario = telaUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxUserProfile = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pswPassword = new javax.swing.JPasswordField();
        pswRepeatPassword = new javax.swing.JPasswordField();
        lblVerifyName = new javax.swing.JLabel();
        lblVerifyEmail = new javax.swing.JLabel();
        lblVerifyPassword = new javax.swing.JLabel();
        lblVerifyRepeatPassword = new javax.swing.JLabel();
        lblVerifyUserProfile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CRIAR USUÁRIO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Senha");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Perfil de Usuário");

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Repetir Senha");

        pswPassword.setEchoChar('*');

        pswRepeatPassword.setEchoChar('*');

        lblVerifyName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblVerifyName.setForeground(new java.awt.Color(255, 0, 0));
        lblVerifyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblVerifyEmail.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblVerifyEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblVerifyEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblVerifyPassword.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblVerifyPassword.setForeground(new java.awt.Color(255, 0, 0));
        lblVerifyPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblVerifyRepeatPassword.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblVerifyRepeatPassword.setForeground(new java.awt.Color(255, 0, 0));
        lblVerifyRepeatPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblVerifyUserProfile.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblVerifyUserProfile.setForeground(new java.awt.Color(255, 0, 0));
        lblVerifyUserProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblVerifyName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblVerifyRepeatPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pswRepeatPassword)
                                    .addComponent(lblVerifyPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblVerifyEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail)
                                    .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVerifyUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVerifyName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVerifyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVerifyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswRepeatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVerifyRepeatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblVerifyUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSave)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Insere um usuário no banco de dados.
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Usuario usuario = new Usuario();
        boolean erro = false;

        usuario.setNome(txtName.getText());
        usuario.setEmail(txtEmail.getText());
        usuario.setSenha(new String(pswPassword.getPassword()));
        usuario.setPerfilUsuario((PerfilUsuario) cbxUserProfile.getSelectedItem());
        
        //Verifica se o campo Nome está preenchido.
        if (txtName.getText().equals("")) {
            lblVerifyName.setText("Informe o nome!");
            erro = true;
        } else {
            lblVerifyName.setText("");
        }
        //Verifica se o campo E-mail está preenchido.
        if (txtEmail.getText().equals("")) {
            lblVerifyEmail.setText("Informe o e-mail!");
            erro = true;
        } else {
            lblVerifyEmail.setText("");
        }
        //Verifica se o campo Senha está preenchido.
        if (new String(pswPassword.getPassword()).equals("")) {
            lblVerifyPassword.setText("Informe a senha!");
            erro = true;
        } else {
            lblVerifyPassword.setText("");
        }
        //Verifica se há um Perfil de Usuário selecionado.
        if (cbxUserProfile.getSelectedItem() == null) {
            lblVerifyUserProfile.setText("Selecione o perfil de usuário!");
            erro = true;
        } else {
            lblVerifyUserProfile.setText("");
        }
        //Verifica se o campo Repetir Senha está vazio ou com uma senha não correspondente.
        if (new String(pswRepeatPassword.getPassword()).equals("")) {
            lblVerifyRepeatPassword.setText("Repita a senha!");
            erro = true;
        } else if (this.validarSenha(usuario) == false && !new String(pswRepeatPassword.getPassword()).equals("")) {
            lblVerifyRepeatPassword.setText("As senhas não correspondem!");
            erro = true;
        } else {
            lblVerifyRepeatPassword.setText("");
        }
        //Se houver algum erro (Campo não preenchido ou senha não correspondente), o usuário não será criado.
        if (erro == true) {
            return;
        }

        try {
            usuarioController.save(usuario);
            JOptionPane.showMessageDialog(null, "Usuário criado com sucesso!");
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, error, "Erro ao criar usuário", JOptionPane.ERROR_MESSAGE);
        }

        this.limparCampos();
        telaUsuario.atualizarTabela();
        dispose();
    }//GEN-LAST:event_btnSaveActionPerformed
    //Insere os perfis de usuário no cbxUserProfile.
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultComboBoxModel<PerfilUsuario> dCBM = (DefaultComboBoxModel<PerfilUsuario>) this.cbxUserProfile.getModel();

        dCBM.addElement(null);
        
        PerfilUsuario paciente = new PerfilUsuario();
        paciente.setNome("Paciente");
        paciente.setDescricao("Acessa e gerencia suas informações de saúde.");
        dCBM.addElement(paciente);
        
        PerfilUsuario enfermeiro = new PerfilUsuario();
        enfermeiro.setNome("Enfermeiro");
        enfermeiro.setDescricao("Realiza cuidados e monitora a saúde dos pacientes.");
        dCBM.addElement(enfermeiro);
        
        PerfilUsuario farmaceutico = new PerfilUsuario();
        farmaceutico.setNome("Farmacêutico");
        farmaceutico.setDescricao("Gerencia prescrições e estoque de medicamentos.");
        dCBM.addElement(farmaceutico);
        
        PerfilUsuario medico = new PerfilUsuario();
        medico.setNome("Médico");
        medico.setDescricao("Acompanha e prescreve tratamentos aos pacientes.");
        dCBM.addElement(medico);
        
        PerfilUsuario secretario = new PerfilUsuario();
        secretario.setNome("Secretário");
        secretario.setDescricao("Organiza agendamentos e documentos administrativos.");
        dCBM.addElement(secretario);
        
        PerfilUsuario gestorSaude = new PerfilUsuario();
        gestorSaude.setNome("Gestor de Saúde");
        gestorSaude.setDescricao("Supervisiona equipes e processos de saúde.");
        dCBM.addElement(gestorSaude);
        
        PerfilUsuario contador = new PerfilUsuario();
        contador.setNome("Contador");
        contador.setDescricao("Administra finanças e faturamento do sistema de saúde.");
        dCBM.addElement(contador);
        
        PerfilUsuario administrador = new PerfilUsuario();
        administrador.setNome("Administrador");
        administrador.setDescricao("Gerencia configurações do sistema e acessos dos usuários.");
        dCBM.addElement(administrador);
    }//GEN-LAST:event_formWindowOpened

    //Verifica se as senhas digitadas nos campos "Senha" e "Repetir Senha" correspondem.
    private Boolean validarSenha(Usuario usuario) {
        if (!usuario.getSenha().equals(new String(pswRepeatPassword.getPassword()))) {
            return false;
        } else {
            return true;
        }
    }

    //Limpa os campos de texto após o cadastro.
    private void limparCampos() {
        txtName.setText("");
        txtEmail.setText("");
        pswPassword.setText("");
        pswRepeatPassword.setText("");
        cbxUserProfile.setSelectedItem(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Realiza a injeção de dependência no UsuarioController.
                UsuarioIController usuarioController = null;
                TelaCriarUsuario telaCriarUsuario = new TelaCriarUsuario(usuarioController);
                telaCriarUsuario.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbxUserProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblVerifyEmail;
    private javax.swing.JLabel lblVerifyName;
    private javax.swing.JLabel lblVerifyPassword;
    private javax.swing.JLabel lblVerifyRepeatPassword;
    private javax.swing.JLabel lblVerifyUserProfile;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JPasswordField pswRepeatPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
