/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.campanhavacina.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import br.com.ifba.campanhavacina.controller.CampanhaVacinaIController;
import br.com.ifba.campanhavacina.entity.CampanhaVacinaEntity;

/**
 *
 * @author a1591
 * Tela responsavel por fazer a procura de um objeto na lista
 * exibindo ao usuario sua procura especifica pelo id
 */

@Component
public class CampanhaVacinaProcurar extends javax.swing.JFrame {
    
    @Autowired
    private CampanhaVacinaIController campanhaVacinaController;
    
    /**
     * Creates new form CursoProcurar
     */
    public CampanhaVacinaProcurar() {
        initComponents();       
        this.setLocationRelativeTo(null); // Centraliza a janela
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fechar esta janela sem afetar as outras
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iDCampanha = new javax.swing.JLabel();
        textFildIdCampanha = new javax.swing.JTextField();
        buttonProcurarCampanha = new javax.swing.JButton();
        jLableMostraCampanha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iDCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iDCampanha.setText("Digite o ID da Campanha :");

        textFildIdCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonProcurarCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonProcurarCampanha.setText("Procurar");
        buttonProcurarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcurarCampanhaActionPerformed(evt);
            }
        });

        jLableMostraCampanha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLableMostraCampanha.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1)
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(buttonProcurarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iDCampanha)
                        .addGap(15, 15, 15)
                        .addComponent(textFildIdCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(338, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLableMostraCampanha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iDCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFildIdCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(buttonProcurarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLableMostraCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void buttonProcurarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcurarCampanhaActionPerformed
        // TODO add your handling code here:
        
        if(textFildIdCampanha.getText().isEmpty()){
            JOptionPane.showMessageDialog(
                    null, 
                    "PREENCHA TODOS OS CAMPOS\n", 
                    "ERRO", 
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
        // Recebe o curso encontrado
        CampanhaVacinaEntity campanhaEncontrada; //new CampanhaVacinaEntity();
        
        // Recebe pelo ID
        campanhaEncontrada = campanhaVacinaController.findById(Long.valueOf(textFildIdCampanha.getText()));
        
        // Exibe as informaçãoes do Curso
        jLableMostraCampanha.setText(campanhaEncontrada.toString());

        
        JOptionPane.showMessageDialog(
                    this,  
                    "Procura bem Sucedida!\n", 
                    "Sucesso", 
                    JOptionPane.INFORMATION_MESSAGE
        );
        
        
    }//GEN-LAST:event_buttonProcurarCampanhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampanhaVacinaProcurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampanhaVacinaProcurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampanhaVacinaProcurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampanhaVacinaProcurar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CampanhaVacinaProcurar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProcurarCampanha;
    private javax.swing.JLabel iDCampanha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLableMostraCampanha;
    private javax.swing.JTextField textFildIdCampanha;
    // End of variables declaration//GEN-END:variables
}
