/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.campanhavacina.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import br.com.ifba.campanhavacina.controller.CampanhaVacinaIController;
import br.com.ifba.campanhavacina.entity.CampanhaVacinaEntity;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 *
 * @author a1591
 * 
 * Nessa view pode ser adicionado objetos a lista !
 */
@Component
public class CampanhaVacinaAdicionar extends javax.swing.JFrame {
    
    @Autowired
    private CampanhaVacinaIController campanhaVacinaController;
        
    /**
     * Creates new form CursoAdicionar
     */
    public CampanhaVacinaAdicionar() {
        initComponents();
        this.setLocationRelativeTo(null); // Centraliza a janela
        
    }
  
    @Autowired
    private GestaoCampanhaVacina listarFrame; // Referência para o frame de listagem

    public CampanhaVacinaAdicionar(GestaoCampanhaVacina listarFrame) {
        initComponents(); // Inicializa os componentes da interface gráfica

        this.listarFrame = listarFrame; // Recebe o frame responsável pela listagem
        
        // Adiciona um listener para detectar o fechamento da janela
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (listarFrame != null) {
                    listarFrame.readJTable(); // Atualiza a tabela no frame de listagem
                }
            }
        });

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fecha esta janela sem encerrar o programa
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teste = new javax.swing.JLabel();
        nomeDaCampanha = new javax.swing.JLabel();
        textFieldNomeCampanha = new javax.swing.JTextField();
        local = new javax.swing.JLabel();
        textFieldLocalDaAplicacao = new javax.swing.JTextField();
        disponibilidadeVacina = new javax.swing.JLabel();
        checkBoxDisponibilidadeVacina = new javax.swing.JCheckBox();
        btnSalvarCampanha = new javax.swing.JButton();
        dataInico = new javax.swing.JLabel();
        textFieldDataInicio = new javax.swing.JTextField();
        publicoAlvo = new javax.swing.JLabel();
        textFieldPublicoAlvo = new javax.swing.JTextField();
        dataFim = new javax.swing.JLabel();
        textFieldDataFim = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teste.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        nomeDaCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeDaCampanha.setText("Nome da Campanha : ");

        textFieldNomeCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        local.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        local.setText("Local Da Aplicação:");

        textFieldLocalDaAplicacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        disponibilidadeVacina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        disponibilidadeVacina.setText("Disponibilidade:");

        checkBoxDisponibilidadeVacina.setText("Atividade");
        checkBoxDisponibilidadeVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDisponibilidadeVacinaActionPerformed(evt);
            }
        });

        btnSalvarCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarCampanha.setText("Salvar");
        btnSalvarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCampanhaActionPerformed(evt);
            }
        });

        dataInico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataInico.setText("Data Inicio:");

        textFieldDataInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldDataInicio.setText("dd/MM/yyyy HH:mm");

        publicoAlvo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        publicoAlvo.setText("Publico Alvo:");

        textFieldPublicoAlvo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dataFim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataFim.setText("Data Fim:");

        textFieldDataFim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldDataFim.setText("dd/MM/yyyy HH:mm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeDaCampanha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNomeCampanha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dataInico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldDataInicio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(local)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldLocalDaAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dataFim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldDataFim))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(publicoAlvo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldPublicoAlvo)))
                        .addGap(61, 61, 61)
                        .addComponent(teste))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSalvarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(disponibilidadeVacina)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(checkBoxDisponibilidadeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(teste)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeDaCampanha)
                            .addComponent(textFieldNomeCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(local)
                            .addComponent(textFieldLocalDaAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataInico)
                    .addComponent(textFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataFim)
                    .addComponent(textFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publicoAlvo)
                    .addComponent(textFieldPublicoAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disponibilidadeVacina)
                    .addComponent(checkBoxDisponibilidadeVacina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnSalvarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSalvarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCampanhaActionPerformed
        // TODO add your handling code here:

        // Salva no banco
        try {
            // Cria um novo objeto do tipo CampanhaVacinaEntity
            CampanhaVacinaEntity campanhaVacinaEntity = new CampanhaVacinaEntity();

            // Define os atributos do objeto com os valores obtidos
            campanhaVacinaEntity.setNome(textFieldNomeCampanha.getText()); // Define o nome da Campanha
            campanhaVacinaEntity.setLocalVacina(textFieldLocalDaAplicacao.getText()); // Local da Campanha

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"); // Formato da data
            
            // Tenta analisar a data de início usando o formatador
            String dataInicioStr = textFieldDataInicio.getText(); // Obtém a string da data
            campanhaVacinaEntity.setInicioCampanha(LocalDateTime.parse(dataInicioStr, formatter)); // Define a data de início

            // Tenta analisar a data final usando o formatador
            String dataFinalStr = textFieldDataFim.getText(); // Obtém a string da data
            campanhaVacinaEntity.setFinalCampanha(LocalDateTime.parse(dataFinalStr, formatter)); // Define a data final

            campanhaVacinaEntity.setDisponibilidade(checkBoxDisponibilidadeVacina.isSelected()); // Define a Disponibilidade da Vacina
            campanhaVacinaEntity.setPublicoAlvo(textFieldPublicoAlvo.getText()); // Define o Público Alvo

            // Salva a campanha no banco
            campanhaVacinaController.save(campanhaVacinaEntity);
            
            // Atualiza a tabela
            listarFrame.readJTable();

            JOptionPane.showMessageDialog(this, "Adicionado com sucesso!", 
                                              "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Fecha a janela atual após o sucesso

        } catch (DateTimeParseException e) {
            // Trate a exceção para formato de data inválido
            JOptionPane.showMessageDialog(this, "Formato de data inválido! Use o formato dd/MM/yyyy HH:mm", 
                                              "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (RuntimeException e) {
            // Trate outras exceções
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), 
                                              "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarCampanhaActionPerformed

    private void checkBoxDisponibilidadeVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDisponibilidadeVacinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxDisponibilidadeVacinaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampanhaVacinaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampanhaVacinaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampanhaVacinaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampanhaVacinaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                GestaoCampanhaVacina listarFrame = new GestaoCampanhaVacina();
                new CampanhaVacinaAdicionar(listarFrame).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarCampanha;
    private javax.swing.JCheckBox checkBoxDisponibilidadeVacina;
    private javax.swing.JLabel dataFim;
    private javax.swing.JLabel dataInico;
    private javax.swing.JLabel disponibilidadeVacina;
    private javax.swing.JLabel local;
    private javax.swing.JLabel nomeDaCampanha;
    private javax.swing.JLabel publicoAlvo;
    private javax.swing.JLabel teste;
    private javax.swing.JTextField textFieldDataFim;
    private javax.swing.JTextField textFieldDataInicio;
    private javax.swing.JTextField textFieldLocalDaAplicacao;
    private javax.swing.JTextField textFieldNomeCampanha;
    private javax.swing.JTextField textFieldPublicoAlvo;
    // End of variables declaration//GEN-END:variables
}
