/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.campanhavacina.view;

import br.com.ifba.campanhavacina.entity.CampanhaVacinaEntity;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;
import br.com.ifba.campanhavacina.controller.CampanhaVacinaIController;
import java.time.format.DateTimeFormatter;
import javax.swing.SwingUtilities;

/**
 *
 * @author a1591
 */

@Component
@Slf4j
public class GestaoCampanhaVacina extends javax.swing.JFrame {
    
    @Autowired
    private ApplicationContext context;
    
    @Autowired
    private CampanhaVacinaIController campanhaVacinaController;
    
    
    public GestaoCampanhaVacina() {
        initComponents();
        
        this.setLocationRelativeTo(null); // Centraliza a janela
        
        // Aguarda a inicialização completa da GUI antes de atualizar a tabela
        // OBS !!! Tirando essa linha, não funciona o readJTable
        SwingUtilities.invokeLater(() -> readJTable());
    }
    
    public void readJTable() {

        log.info("🔄 Atualizando a tabela...");

        // Verifica se o controller foi injetado corretamente
        if (campanhaVacinaController == null) {
            log.error("❌ ERRO: cursoController nao foi injetado corretamente!");
            return;
        }

        // Verifica se tem objeto no banco
        List<CampanhaVacinaEntity> campanhas = campanhaVacinaController.findAll();
        if (campanhas == null || campanhas.isEmpty()) {
            log.warn("⚠ Nenhum curso encontrado.");
            return;
        }

        // Verifica de a tablea está nulla
        if (tabelaExibirCampanha == null) {
            log.error("❌ ERRO: tabelaExibir está nula!");
            return;
        }

        // Obtem o modelo da tabela e verifica se tá nullo
        DefaultTableModel model = (DefaultTableModel) tabelaExibirCampanha.getModel();
        if (model == null) {
            log.error("❌ ERRO: O modelo da tabela está nulo!");
            return;
        }

        // Limpa a tabela antes exibir
        model.setRowCount(0); 

        
        // Popula o banco
        // Popula a tabela
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"); // Formato desejado
        for (CampanhaVacinaEntity c : campanhas) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getLocalVacina(),
                c.getInicioCampanha().format(formatter),
                c.getFinalCampanha() != null ? c.getFinalCampanha().format(formatter) : "N/A",// Verifica se finalCampanha é nulo
                c.isDisponibilidade() ? "Sim" : "Não",
                c.getPublicoAlvo(),
            });
        }
        log.info("✅ Tabela atualizada com sucesso!");
    }

    /**
     * Creates new form AgenteCampanhaVacina
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonProcurarCurso = new javax.swing.JButton();
        scrollTabelaDeInfo = new javax.swing.JScrollPane();
        tabelaExibirCampanha = new javax.swing.JTable();
        buttonAtualizarCampanha = new javax.swing.JButton();
        buttonExcluirCampanha = new javax.swing.JButton();
        buttonEditarCampanha = new javax.swing.JButton();
        buttonAdicionarCampanha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonProcurarCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonProcurarCurso.setText("Procurar Campanha");
        buttonProcurarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcurarCursoActionPerformed(evt);
            }
        });

        tabelaExibirCampanha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Local", "Data Inicio", "Data Fim", "Disponibilidade", "Publico Alvo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaExibirCampanha.setToolTipText("");
        scrollTabelaDeInfo.setViewportView(tabelaExibirCampanha);

        buttonAtualizarCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAtualizarCampanha.setText("Atualizar Tabela de Campanha");
        buttonAtualizarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarCampanhaActionPerformed(evt);
            }
        });

        buttonExcluirCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonExcluirCampanha.setText("Excluir Campanha");
        buttonExcluirCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirCampanhaActionPerformed(evt);
            }
        });

        buttonEditarCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonEditarCampanha.setText("Editar Campanha");
        buttonEditarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarCampanhaActionPerformed(evt);
            }
        });

        buttonAdicionarCampanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAdicionarCampanha.setText("Adicionar Campanha");
        buttonAdicionarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarCampanhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTabelaDeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAtualizarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonExcluirCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEditarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdicionarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProcurarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(buttonAtualizarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAdicionarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEditarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonExcluirCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonProcurarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 33, Short.MAX_VALUE)
                        .addComponent(scrollTabelaDeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProcurarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcurarCursoActionPerformed
        // TODO add your handling code here:
        
        // Abre a tela ao apertar o botão
        CampanhaVacinaProcurar cursoProcurar = context.getBean(CampanhaVacinaProcurar.class); 
        
        cursoProcurar.setDefaultCloseOperation(CampanhaVacinaEditar.DISPOSE_ON_CLOSE);
        cursoProcurar.setVisible(true);      
    }//GEN-LAST:event_buttonProcurarCursoActionPerformed

    private void buttonAtualizarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarCampanhaActionPerformed
        // TODO add your handling code here:
        
        
        // Atualiza a lista, exibe ela atualizada
        readJTable();
    }//GEN-LAST:event_buttonAtualizarCampanhaActionPerformed

    private void buttonExcluirCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirCampanhaActionPerformed
        // TODO add your handling code here:
        
        // Abre a tela ao apertar o botão
        CampanhaVacinaExcluir cursoExcluir = context.getBean(CampanhaVacinaExcluir.class);
        
        cursoExcluir.setDefaultCloseOperation(CampanhaVacinaExcluir.DISPOSE_ON_CLOSE);
        cursoExcluir.setVisible(true);    
    }//GEN-LAST:event_buttonExcluirCampanhaActionPerformed

    private void buttonEditarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarCampanhaActionPerformed
        // TODO add your handling code here:
        
        // Abre a tela ao apertar o botão
        CampanhaVacinaEditar cursoEditar = context.getBean(CampanhaVacinaEditar.class);
        
        cursoEditar.setDefaultCloseOperation(CampanhaVacinaEditar.DISPOSE_ON_CLOSE);
        cursoEditar.setVisible(true);
    }//GEN-LAST:event_buttonEditarCampanhaActionPerformed

    private void buttonAdicionarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarCampanhaActionPerformed
        // TODO add your handling code here:
        
        // Abre a tela ao apertar o botão
        CampanhaVacinaAdicionar campanhaVacinaAdicionar = context.getBean(CampanhaVacinaAdicionar.class);
        
        campanhaVacinaAdicionar.setDefaultCloseOperation(CampanhaVacinaEditar.DISPOSE_ON_CLOSE);
        campanhaVacinaAdicionar.setVisible(true);
        
    }//GEN-LAST:event_buttonAdicionarCampanhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoCampanhaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoCampanhaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoCampanhaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoCampanhaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {              
                GestaoCampanhaVacina listarFrame = new GestaoCampanhaVacina();
                listarFrame.setVisible(true); // Certifique-se de mostrar o frame principal
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarCampanha;
    private javax.swing.JButton buttonAtualizarCampanha;
    private javax.swing.JButton buttonEditarCampanha;
    private javax.swing.JButton buttonExcluirCampanha;
    private javax.swing.JButton buttonProcurarCurso;
    private javax.swing.JScrollPane scrollTabelaDeInfo;
    private javax.swing.JTable tabelaExibirCampanha;
    // End of variables declaration//GEN-END:variables
}
